
security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_USER:        ROLE_QUEST_CONSULTER
       ROLE_ADMIN:       [ROLE_USER, ROLE_QUEST_AJOUTER]
       ROLE_SUPER_ADMIN: ROLE_ADMIN

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
       dev:
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false
       main:
           pattern: .*
           context:            user
           form_login:
               provider: fos_userbundle
               check_path: /login_check
               login_path: /login/
               use_forward: false
               failure_path:   null
               default_target_path:   /
#               csrf_provider: form.csrf_provider
           logout:
               path:    /logout
               target:  /login/
           anonymous:          true
#           remember_me:
#               key: %secret%
#               lifetime: 86400
#               path: /
#                   domain: ~

   access_control:
       - { path: ^/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # Secured part of the site
               # This config requires being logged for the whole site and having the admin role for the admin part.
               # Change these rules to adapt them to your needs
       - { path: ^/.*, role: ROLE_USER }