# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app_bundle.menu_listener.class: AppBundle\EventListener\SidebarSetupMenuListener
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app_bundle_bundle.menu_listener:
        class: %app_bundle.menu_listener.class%
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }
    app_bundle.breadcrumb_listener:
                class: %app_bundle.menu_listener.class%
                tags:
                    - { name: kernel.event_listener, event:theme.breadcrumb, method:onSetupMenu }